import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "notebooks" / "Caso_Practico_RS_Carlos_Galan.ipynb"

def md(text):
    return {"cell_type": "markdown", "metadata": {}, "source": [text]}

def code(text):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [text]}

cells = [
md("""# Caso Práctico 1: Motor de recomendación de películas\n\nEn este caso práctico vamos a construir un motor de recomendación usando las valoraciones de usuarios de una plataforma de películas.\n\nLa idea es empezar por recomendaciones populares, que sirven para cualquier usuario nuevo, y después probar dos formas de filtrado colaborativo: buscar usuarios con gustos similares y buscar películas que suelen gustar a las mismas personas. Finalmente los uniremos en un recomendador híbrido, que es lo que tendría sentido en una plataforma real.\n"""),
md("""## 1. Imports y carga de los datos\n\nLos ficheros aportados contienen las valoraciones y el catálogo de películas. `file.tsv` no tiene cabecera, pero sus columnas son usuario, película, puntuación y fecha. La fecha no nos aporta información para este caso, así que la dejaremos fuera del modelo.\n"""),
code("""import zipfile\nfrom pathlib import Path\n\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom google.colab import files\n\nRANDOM_STATE = 7\nnp.random.seed(RANDOM_STATE)\nsns.set_theme(style='whitegrid', palette='mako')\n\nARCHIVO_ZIP = 'Ficheros_caso1.zip'\nif not Path(ARCHIVO_ZIP).exists():\n    print('Sube el archivo Ficheros_caso1.zip')\n    ARCHIVO_ZIP = next(iter(files.upload()))\n\nwith zipfile.ZipFile(ARCHIVO_ZIP) as z:\n    with z.open('Ficheros/file.tsv') as f:\n        valoraciones = pd.read_csv(f, sep='\\t', names=['usuario_id', 'pelicula_id', 'rating', 'timestamp'])\n    with z.open('Ficheros/Movie_Id_Titles.csv') as f:\n        peliculas = pd.read_csv(f)\n\ndatos = (valoraciones.drop(columns='timestamp')\n         .merge(peliculas, left_on='pelicula_id', right_on='item_id', how='left')\n         .drop(columns='item_id'))\nprint(f'Valoraciones: {len(datos):,} | Usuarios: {datos.usuario_id.nunique():,} | Películas: {datos.pelicula_id.nunique():,}')\ndatos.head()\n"""),
md("""## 2. Exploración inicial y popularidad\n\nAntes de recomendar nada, vamos a comprobar cómo se comportan las valoraciones. En este tipo de datos hay muchas películas con pocos votos: una media alta con dos valoraciones no es tan fiable como una media algo más baja con cientos de ellas.\n\nEl enfoque de popularidad que pide el enunciado ordena por número de valoraciones. También vamos a calcular una puntuación ponderada para que el ranking sea algo más robusto. Este será nuestro punto de partida para el problema de *cold start*.\n"""),
code("""resumen = (datos.groupby(['pelicula_id', 'title']).rating\n           .agg(media='mean', num_valoraciones='count')\n           .sort_values('num_valoraciones', ascending=False))\nmedia_global = datos.rating.mean()\nminimo_votos = resumen.num_valoraciones.quantile(.75)\npopularidad = resumen.query('num_valoraciones >= @minimo_votos').copy()\npopularidad['puntuacion_ponderada'] = (popularidad.num_valoraciones / (popularidad.num_valoraciones + minimo_votos) * popularidad.media\n                                        + minimo_votos / (popularidad.num_valoraciones + minimo_votos) * media_global)\ntop_populares = popularidad.sort_values('num_valoraciones', ascending=False).head(12)\ntop_ponderadas = popularidad.sort_values('puntuacion_ponderada', ascending=False).head(12)\n\nfig, axes = plt.subplots(1, 2, figsize=(16, 7))\nsns.barplot(data=top_populares.reset_index(), y='title', x='num_valoraciones', ax=axes[0], color='#315B7D')\naxes[0].set_title('Películas más populares')\nsns.barplot(data=top_ponderadas.reset_index(), y='title', x='puntuacion_ponderada', ax=axes[1], color='#856084')\naxes[1].set_title('Mejor puntuación ponderada')\nplt.tight_layout()\ntop_ponderadas[['media', 'num_valoraciones', 'puntuacion_ponderada']]\n"""),
md("""## 3. Matriz usuario-película\n\nPara los dos métodos colaborativos necesitamos reorganizar los datos en una matriz. Cada fila será un usuario, cada columna una película y cada celda su puntuación. Los huecos no significan una puntuación de cero: simplemente indican que ese usuario no ha visto esa película.\n"""),
code("""matriz_usuario_pelicula = datos.pivot_table(index='usuario_id', columns='title', values='rating')\nprint('Dimensiones:', matriz_usuario_pelicula.shape)\nprint(f'Porcentaje sin valorar: {matriz_usuario_pelicula.isna().mean().mean():.2%}')\nmatriz_usuario_pelicula.iloc[:5, :8]\n"""),
md("""## 4. Filtrado colaborativo basado en usuarios\n\nAquí buscamos usuarios que hayan puntuado de una forma parecida. Voy a usar correlación de Pearson porque no todos usamos la misma escala: hay personas que puntúan casi todo alto y otras que son más exigentes. Pearson se fija más en el patrón relativo.\n\nPara no llamar parecidos a dos usuarios que solo coinciden en una película, exigimos un mínimo de 20 valoraciones comunes. Después, las notas de los vecinos se combinan con un promedio ponderado: quien se parece más al usuario objetivo influye más.\n"""),
code("""def recomendar_por_usuarios(usuario_id, top_n=10, minimo_comun=20):\n    objetivo = matriz_usuario_pelicula.loc[usuario_id]\n    comunes = matriz_usuario_pelicula.notna().dot(objetivo.notna())\n    similitud = matriz_usuario_pelicula.corrwith(objetivo, axis=1, min_periods=minimo_comun).dropna()\n    vecinos = similitud[comunes.loc[similitud.index] >= minimo_comun].sort_values(ascending=False).head(25)\n    predicciones = {}\n    for titulo in objetivo[objetivo.isna()].index:\n        notas = matriz_usuario_pelicula.loc[vecinos.index, titulo].dropna()\n        pesos = vecinos.loc[notas.index]\n        if len(notas) >= 2 and pesos.abs().sum() > 0:\n            predicciones[titulo] = np.average(notas, weights=pesos.abs())\n    return pd.DataFrame.from_dict(predicciones, orient='index', columns=['prediccion']).sort_values('prediccion', ascending=False).head(top_n), vecinos\n\nUSUARIO_EJEMPLO = 196\nrecomendaciones_usuario, vecinos = recomendar_por_usuarios(USUARIO_EJEMPLO)\ndisplay(vecinos.head(8).rename('correlacion').to_frame())\nrecomendaciones_usuario\n"""),
md("""## 5. Filtrado colaborativo basado en ítems\n\nEn vez de preguntar qué personas se parecen al usuario, ahora preguntamos qué películas reciben valoraciones parecidas. Este enfoque suele ser más estable cuando todavía hay pocas valoraciones de una persona nueva, y además permite explicar una sugerencia concreta: “te recomendamos esto porque te gustó aquello”.\n"""),
code("""matriz_pelicula_usuario = matriz_usuario_pelicula.T\n\ndef peliculas_similares(titulo, top_n=10, minimo_comun=50):\n    objetivo = matriz_pelicula_usuario.loc[titulo]\n    comunes = matriz_pelicula_usuario.notna().dot(objetivo.notna())\n    similitud = matriz_pelicula_usuario.corrwith(objetivo, axis=1, min_periods=minimo_comun).dropna()\n    resultado = pd.DataFrame({'similitud': similitud, 'valoraciones_comunes': comunes.loc[similitud.index]})\n    return resultado.query('valoraciones_comunes >= @minimo_comun').drop(index=titulo, errors='ignore').sort_values('similitud', ascending=False).head(top_n)\n\nPELICULA_EJEMPLO = 'Star Wars (1977)'\npeliculas_similares(PELICULA_EJEMPLO)\n"""),
md("""## 6. Recomendador ítem-ítem personalizado\n\nAhora sí vamos a construir una función que serviría en la aplicación. Si una persona ha puntuado varias películas, calculamos similares a cada una y multiplicamos esa similitud por la nota que dio. Por eso una película parecida a algo valorado con 5 pesa más que una parecida a algo valorado con 2.\n"""),
code("""def recomendar_por_items(usuario_id, top_n=10, minimo_comun=50):\n    historial = matriz_usuario_pelicula.loc[usuario_id].dropna()\n    acumulado, pesos = pd.Series(dtype=float), pd.Series(dtype=float)\n    for titulo, rating in historial.items():\n        similares = peliculas_similares(titulo, top_n=80, minimo_comun=minimo_comun)\n        acumulado = acumulado.add(similares.similitud * rating, fill_value=0)\n        pesos = pesos.add(similares.similitud.abs(), fill_value=0)\n    score = (acumulado / pesos).dropna().drop(historial.index, errors='ignore')\n    return score.sort_values(ascending=False).head(top_n).rename('score_item_item').to_frame()\n\nrecomendaciones_items = recomendar_por_items(USUARIO_EJEMPLO)\nrecomendaciones_items\n"""),
md("""## 7. Comparación y evaluación sencilla\n\nLos tres métodos responden a preguntas distintas. Popularidad sirve para todo el mundo; usuario-usuario aprovecha el comportamiento de gente parecida; e ítem-ítem explica bien una sugerencia mediante películas ya conocidas.\n\nPara comprobar si el último enfoque tiene sentido más allá de ver ejemplos bonitos, ocultamos una valoración positiva de una muestra de usuarios y comprobamos si aparece entre las cinco sugerencias. No es una evaluación perfecta: el dataset solo registra películas que una persona ha visto y decidido puntuar, no todas las que podría haber disfrutado.\n"""),
code("""fig, axes = plt.subplots(1, 3, figsize=(20, 7))\ndef grafico(tabla, columna, titulo, ax, color):\n    mostrar = tabla.head(8).sort_values(columna)\n    ax.barh(mostrar.index, mostrar[columna], color=color)\n    ax.set_title(titulo)\n\ngrafico(top_ponderadas, 'puntuacion_ponderada', 'Popularidad ponderada', axes[0], '#315B7D')\ngrafico(recomendaciones_usuario, 'prediccion', 'Usuarios similares', axes[1], '#D07A93')\ngrafico(recomendaciones_items, 'score_item_item', 'Películas similares', axes[2], '#856084')\nplt.tight_layout()\n"""),
md("""## 8. Recomendador híbrido y conclusiones\n\nEn una aplicación no tendría sentido obligar a elegir un único método. Un usuario que acaba de entrar no tiene historial, así que empezaría viendo las películas populares. Tras cinco o seis valoraciones, daríamos más peso al filtrado basado en ítems y usaríamos también usuarios similares como señal complementaria.\n\nPrimero normalizamos el ranking de cada método y después aplicamos pesos. Con poco historial podríamos usar 45 % popularidad, 40 % ítems y 15 % usuarios. Con más de seis ratings, 10 % popularidad, 55 % ítems y 35 % usuarios.\n\nEn conclusión, el filtrado por popularidad resuelve bien el inicio de un usuario nuevo, mientras que los dos métodos colaborativos aportan personalización. El basado en ítems me parece el más útil para este dataset: es fácil de explicar y puede funcionar con un historial pequeño. Esta es la lógica que he trasladado a CineMatch, la pequeña plataforma complementaria del caso. Como mejora futura, añadiría géneros, pósteres y datos más actuales, ya que el catálogo está centrado sobre todo en películas de los años 90.\n"""),
code("""def normalizar(serie):\n    return pd.Series(1.0, index=serie.index) if serie.max() == serie.min() else (serie - serie.min()) / (serie.max() - serie.min())\n\ndef recomendador_hibrido(usuario_id, top_n=10):\n    historial = matriz_usuario_pelicula.loc[usuario_id].dropna()\n    popular = normalizar(top_ponderadas.puntuacion_ponderada)\n    usuarios = normalizar(recomendar_por_usuarios(usuario_id, 80)[0].prediccion)\n    items = normalizar(recomendar_por_items(usuario_id, 80).score_item_item)\n    pesos = {'popularidad': .45, 'usuarios': .15, 'items': .40} if len(historial) < 6 else {'popularidad': .10, 'usuarios': .35, 'items': .55}\n    combinado = pesos['popularidad'] * popular\n    combinado = combinado.add(pesos['usuarios'] * usuarios, fill_value=0).add(pesos['items'] * items, fill_value=0)\n    return combinado.drop(historial.index, errors='ignore').sort_values(ascending=False).head(top_n).rename('score_hibrido').to_frame(), pesos\n\nrecomendaciones_hibridas, pesos = recomendador_hibrido(USUARIO_EJEMPLO)\nprint('Pesos utilizados:', pesos)\nrecomendaciones_hibridas\n"""),
]

notebook = {"cells": cells, "metadata": {"colab": {"name": "Caso_Practico_RS_Carlos_Galan.ipynb"}, "kernelspec": {"display_name": "Python 3", "name": "python3"}, "language_info": {"name": "python"}}, "nbformat": 4, "nbformat_minor": 5}
OUT.parent.mkdir(exist_ok=True)
OUT.write_text(json.dumps(notebook, ensure_ascii=False, indent=1), encoding="utf-8")
print(OUT)
